# Generated by Django 5.2.1 on 2025-06-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carApp', '0002_alter_cars_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='price',
            field=models.CharField(max_length=50),
        ),
    ]
