# Generated by Django 5.2.1 on 2025-06-13 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carApp', '0003_alter_cars_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_cc', models.IntegerField()),
                ('engine_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='cars',
            name='engine',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='carApp.engine'),
        ),
    ]
