# Generated by Django 5.2.1 on 2025-06-13 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carApp', '0004_engine_cars_engine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='engine',
            name='engine_type',
        ),
        migrations.AddField(
            model_name='cars',
            name='features',
            field=models.ManyToManyField(null=True, to='carApp.feature'),
        ),
        migrations.AddField(
            model_name='cars',
            name='manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carApp.manufacturer'),
        ),
    ]
